### ISSUE TITLE
Unable to deploy to Dev ORG. Getting fatal error

### ISSUE THREAD

**Issue by Jailalwani** [trailheadapps/ebikes-lwc#100]
Hi,

Followed the instruction to deploy to Dev Org

sfdx force:source:deploy -p force-app/main/default -u ebikesDE

errors out with the following

=== Component Failures [2]
TYPE   FILE                             NAME  PROBLEM
─────  ───────────────────────────────  ────  ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error  sdx_sourceDeploy_1571519870746/        You can’t remove the lightning__RecordPage,lightning__AppPage,lightning__HomePage target from targets, because the component is part of a managed package.
Error  sdx_sourceDeploy_1571519870746/        You can’t remove the lightning__RecordPage,lightning__AppPage,lightning__HomePage target from targets, because the component is part of a managed package.

Any HELP ?

Thanks
Jai

### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot or code snippets_.

**Comment by pozil** [comment]
Hi @Jailalwani, can you check if you have some packages already installed on your Developer Edition?
We're not using packages in this sample app so you should not see traces of managed package in your error logs.

**Comment by Jailalwani** [comment]
Hi @pozil Thank You for looking into this.

I only have the sample recipe installed and do not think it should have interfered with eBikes.

Now here is the interesting part, created a new developer Org and everything went well.

However still curious why in my earlier developer Org, it errors out. 2 Sample Apps which in this case is eBikes and Recipe should be able to coexist.

Regards
Jai

**Comment by pozil** [comment]
Hi @Jailalwani sample apps aren't meant to coexist on the same org. That could work in some cases but it's not something we support.

The error that you saw is probably related to component conflicts. For example, both project have components called `ldsUtils` and `pubsub`. Depending on how you install the sample apps (with or without a package) and in which order, there can be different outcomes.

**Comment by imTachu** [comment]
just for completion if someone lands on this page having this issue in general and not in the ebikes app, there's a [KI](https://trailblazer.salesforce.com/issues_view?id=a1p3A000001pMpqQAE): We can't remove targets (like... ever it seems, the KI says NO FIX)
