### ISSUE TITLE
[BUG STEP 4] Installing E-Bikes using a Scratch Org

### ISSUE THREAD

**Issue by Nashle** [trailheadapps/ebikes-lwc#102]
### Summary

I just created a new Trailhead Playground.

When I follow the installation instructions in step 4 :
> 4. Create a scratch org and provide it with an alias (ebikes in the command below):
> sfdx force:org:create -s -f config/project-scratch-def.json -a ebikes

My terminal displays the following message:

<img width="731" alt="Capture" src="https://user-images.githubusercontent.com/57761581/69557811-7f6c9900-0fa7-11ea-9818-ce1993b63b87.PNG">

### Steps To Reproduce:

1. Create a new Trailhead Playground environment.
2. Follow the installation instructions up to step 4

### Expected result

Succes

### Actual result

Component Failures

**Comment by pozil** [comment]
Hi @Nashle, looking at your error logs, I see that you are trying to deploy using API version v45.0.
You need to update your Salesforce DX install to use the current version v47.0 by running `sfdx update`.

**Comment by Nashle** [comment]
Hi @pozil, I just updated Salesforce DX, I now have the right result. I thank you for your assistance.
