### ISSUE TITLE
Update Prettier to 1.19.x and implement XML support

### ISSUE THREAD

**Issue by muenzpraeger** [trailheadapps/ebikes-lwc#104]
**What is missing from the application? Please describe.**
XML formatting is currently not enforced.
    
**Describe the solution you'd like**
With Prettier 1.19.x and forward XML support got added. For that the [Pretter XML Plugin](https://github.com/prettier/plugin-xml) needs to be added as dev dependency, and the scripts need to be updated.

**Comment by pozil** [comment]
@muenzpraeger I just tried that and the outcome is not so good.
Prettier modifies about 150 `*-meta.xml` files and that causes a series of deployment errors.
Ignoring `*-meta.xml` only prettifies `/mdapiDeploy/unpackaged/package.xml`. All in all, the added value of prettifying xml is rather limited for this project.
Let me know if you want to proceed anyway.

**Comment by muenzpraeger** [comment]
Please assess the reason of deployment errors, and raise issues accordingly to the team.

**Comment by pozil** [comment]
Found a first issue that could be the source: prettier introduces line breaks in tag content and our metadata API doesn't like that for certain types like booleans.

Example in `force-app/main/default/sites/E_Bikes.site-meta.xml`:

```xml
<referrerPolicyOriginWhenCrossOrigin>true</referrerPolicyOriginWhenCrossOrigin>
```
is prettified to:

```xml
<referrerPolicyOriginWhenCrossOrigin>
  true
</referrerPolicyOriginWhenCrossOrigin>
```

This causes the following error when pushing source (scroll right to see the error message):
```
Error parsing file: '
                                                                                           true
                                                                                       ' is not valid for type xsd:boolean, should be '0', '1', 'true' or 'false' (23:43)
```

I assume that values are not trimmed when parsed by our backend.

**Comment by pozil** [comment]
There's no Prettier rule to prevent that from happening in XML so the only option would be to ask the Metadata API team to change their parsing code. TBH I'm not willing to dedicate more energy to this because these files are auto generated and should generally not be hand edited.
Feel free to push that as a bug but I think that we can proceed with `*-meta.xml` in `.prettierignore`.

**Comment by muenzpraeger** [comment]
I opened a bug on that repo. Ignoring the files is not an option, we should work with the plugin author to resolve these kinds of issues.

**Comment by pozil** [comment]
Ok, sorry, I thought that you wanted to change things on the metadata API parser.
It looks like we aren't the only ones having issues with whitespaces formatting so there's a change that this can be addressed by the prettier plugin.

**Comment by pozil** [comment]
Prettier xml plugin bug is now fixed. PR #108 is updated with the new plugin version and it works fine.
Please review @muenzpraeger.
