### ISSUE TITLE
[BUG STEP 4] Installing E-Bikes using a Scratch Org

### ISSUE THREAD

**Issue by hikari-jp** [trailheadapps/ebikes-lwc#105]
when i do step 4 , I failed.Can you help me.

>4.Create a scratch org and provide it with an alias (ebikes in the command below):

sfdx force:org:create -s -f config/project-scratch-def.json -a ebikes

=== Component Failures [4]
TYPE   FILE               NAME                 PROBLEM
─────  ─────────────────  ───────────────────  ───────────────────────────────
───────────────────────────────────────────────────────────────────────────
────────────────────────────────────────────────────────────────
Error  shape/package.xml  Communities          The object 'Communities' of type Settings was included in the manifest file package.xml but the associated settings metadata is missing from the 'settings' folder
Error  shape/package.xml  LightningExperience  The object 'LightningExperience' of type Settings was included in the manifest file package.xml but the
associated settings metadata is missing from the 'settings' folder
Error  shape/package.xml  Mobile               The object 'Mobile' of type Settings was included in the manifest file package.xml but the associated settings metadata is missing from the 'settings' folder
Error  shape/package.xml  Security             The object 'Security' of type Settings was included in the manifest file package.xml but the associated
settings metadata is missing from the 'settings' folder

**Comment by pozil** [comment]
Hi @hikari-jp, can you make sure that your version of Salesforce DX is up to date?
Run `sfdx update` to check that.

**Comment by hikari-jp** [comment]
thank for your answer. I think it is not the reason.

 S:\SFDX\ebikes-lwc>sfdx update
sfdx-cli: Updating CLI... already on latest version: 7.33.2-045d48473e

S:\SFDX\ebikes-lwc> sfdx plugins --core
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 47.6.2 (core)
├─ salesforcedx-templates 47.6.2 (core)
└─ salesforce-alm 47.9.0 (core)

sfdx-cli 7.33.2 (core)

**Comment by hikari-jp** [comment]
when i open the project, my vscode displays this error.
is it the reason?
---------------
Failed to load module. If you have prettier or plugins referenced in package.json, ensure you have run `npm install` Attempted to load prettier from package.json

**Comment by hikari-jp** [comment]
4. sfdx force:org:create -s -f config/project-scratch-def.json -a ebikes
it failed.
And I tried step 5 at this situation. it also failed.

S:\SFDX\ebikes-lwc>sfdx force:source:push
PROJECT PATH                                                                                       ERROR
───────────────────────────────────────────────────────────────────────────
──────────────────────  ────────────────────────────────────────────────────
───────────────────────────────────────────────────────────────────────────
──────────────
force-app\main\default\networks\E-Bikes.network-meta.xml                                           Not available for deploy for this organization
force-app\main\default\navigationMenus\Default_Navigation.navigationMenu-meta.xml                  Not available for deploy for this organization
force-app\main\default\objects\Product_Family__c\listViews\All_Product_Families.listView-meta.xml  SharedTo not allowed:roleAndSubordinatesInternal - CEO (106:19)
force-app\main\default\objects\Account\listViews\All_Acounts.listView-meta.xml                     SharedTo not allowed:roleAndSubordinatesInternal - CEO (103:19)
force-app\main\default\sites\E_Bikes.site-meta.xml                                                 Communities must be enabled before deploying a Chatter Network Site
force-app\main\default\siteDotComSites\E_Bikes_C.site                                              You don't have the correct site publisher privileges for this operation Site : E-Bikes, type: Site.com コミュニティ(db=C,api=ChatterNetworkPicasso)
force-app\main\default\networkBranding\cbE_Bikes.networkBranding                                   Network not found for the CustomBrand : cbE_Bikes
force-app\main\default\layouts\Case-Case Layout.layout-meta.xml                                    In field: QuickAction - no QuickAction named Case.CaseComment found
ERROR running force:source:push:  Push failed.

**Comment by pozil** [comment]
Hi @hikari-jp, thanks for confirming that Salesforce DX is up to date.
The warning about Prettier will not impact the installation so you can safely ignore it.
Step 5 requires step 4 so we need to fix step 4 first.

Looks like you are unable to create a scratch org and I'm not sure that it is related to this project.
Have you already succeeded to do that in another project or is it the first time you try this?

You can try that in a blank project by running:
```
sfdx force:project:create -n test-scratch
cd test-scratch
sfdx force:org:create -s -f config/project-scratch-def.json -a test-scratch
```

Let me know the outcome and we can figure out a path forward.

**Comment by hikari-jp** [comment]
thank you for help.
I try it once more  at another pc.
and it worked although t donnot know the reason.
i am a beginner.

**Comment by pozil** [comment]
Sure no worries, I'm happy to hear that you were able to make it work.
We've all been beginners at some point ;)

**Comment by hikari-jp** [comment]
i am sorry.
when i  deploy it, i failed. would you tell me how to do

PS D:\SFDX\ebikes-lwc> sfdx force:source:deploy -p force-app -u XXX
PROJECT PATH
  ERROR
─────────────────────────────────────────────────────────────────────────────────────────────────  ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
force-app\main\default\networks\E-Bikes.network-meta.xml
  Not available for deploy for this organization
force-app\main\default\navigationMenus\Default_Navigation.navigationMenu-meta.xml
force-app\main\default\objects\Case\fields\Product__c.field-meta.xml
  Cannot update a field to a Lookup, MasterDetail, or Hierarchy from something else (44:13)      
force-app\main\default\objects\Account\listViews\All_Acounts.listView-meta.xml
  SharedTo not allowed:roleAndSubordinatesInternal - CEO (103:19)
force-app\main\default\objects\Product_Family__c\listViews\All_Product_Families.listView-meta.xml  SharedTo not allowed:roleAndSubordinatesInternal - CEO (106:19)
force-app\main\default\sites\E_Bikes.site-meta.xml
  Communities must be enabled before deploying a Chatter Network Site
force-app\main\default\siteDotComSites\E_Bikes_C.site
  You don't have the correct site publisher privileges for this operation Site : E-Bikes, type: Site.com Community(db=C,api=ChatterNetworkPicasso)
force-app\main\default\networkBranding\cbE_Bikes.networkBranding
  Network not found for the CustomBrand : cbE_Bikes
force-app\main\default\layouts\Case-Case Layout.layout-meta.xml
  In field: QuickAction - no QuickAction named Case.CaseComment found
ERROR running force:source:deploy:  Deploy failed.

**Comment by hikari-jp** [comment]
i am sorry. i did it.
i hadnot do it
Installing E-Bikes using a Developer Edition Org

**Comment by pozil** [comment]
You got me confused here. Do you still need help?
