### ISSUE TITLE
Implement WITH_SECURITY_ENFORCED in SOQL

### ISSUE THREAD

**Issue by muenzpraeger** [trailheadapps/ebikes-lwc#138]
**What is missing from the application? Please describe.**
With Spring '20 a new security option `WITH _SECURITY_ENFORCED` is available. This is not reflected in the codebase.
    
**Describe the solution you'd like**
The code base needs to be checked if/where it makes sense to apply the option.
    
**Describe alternatives you've considered**
None.

**Comment by pozil** [comment]
Not needed for this app.

**Comment by pozil** [comment]
My bad, it was indeed needed.

**Comment by pozil** [comment]
@codefriar can you assign me for review on these PRs?
