### ISSUE TITLE
I cannot create a scratch org

### ISSUE THREAD

**Issue by sfortunato-dev** [trailheadapps/ebikes-lwc#157]
Please help. I keep getting an error while doing step # 4. 

![image](https://user-images.githubusercontent.com/61812218/75943670-9c7f0500-5ed0-11ea-92d9-c081ea9d335f.png)

I've already updated the version to the latest one. I've had no issues with steps 2 & 3.

**Comment by pozil** [comment]
The error states that the CLI cannot find the scratch org configuration file.
Can you make sure that you run the `force:org:create` command from within the project directory? I suspect that you are doing that from the parent directory.

**Comment by sfortunato-dev** [comment]
Thanks pozil, that did the trick. 

Sadly, I'm met with other issues but I don't think it has something to do specifically with e-bikes lwc rather than my setup. I think I'll complete a few more trailhead modules first to get a better understanding of the deployment process.

Thanks again.
