### ISSUE TITLE
Two suggestions to readme

### ISSUE THREAD

**Issue by garrrychan** [trailheadapps/ebikes-lwc#158]
Two missing instructions are to enable the following in your scratch org before pushing the app.
1. Setup > Communities Settings > Enable Communities (error: You must have My Domain deployed to use component c:pageTemplate_2_7_3)
2. Setup > Development > Dev Hub > Enable Dev Hub (error: You do not have access to the [ScratchOrgInfo] object)

These were not intuitive to me (although somewhat easy to query and fix).

I think these will help people fully set up the app and see what's possible with the ebikes example!

**Comment by pozil** [comment]
Hi, you are probably mixing the instructions for the different org types. You can install the sample app on a Develop Edition (DE) org or on a Scratch org. The readme has separate instructions for these two environments.

**Enabling Communities**
This is only required for DE orgs (step 3).

**Enabling Dev Hub**
This is only required for Scratch orgs (step 1).
