### ISSUE TITLE
Developer Org Step 8 Issue: no ApexPage named CommunitiesLanding found

### ISSUE THREAD

**Issue by melissajhansen** [trailheadapps/ebikes-lwc#162]
### Summary

If you are following the Developer Org Instructions, there are issues in step 8.  After you update the E_Bikes.site-meta.xml
### Steps To Reproduce:

1.  Follow Developer Org Instructions to step 8
1. Try to deploy your change to the E_Bikes.site-meta.xml file

### Expected result

Successful deploy.

### Actual result

You get this error, because you do not have the Visualforce page it is expecting.  indexPage is required, so you can't leave it out. : "force-app/main/default/sites/E_Bikes.site-meta.xml  In field: indexPage - no ApexPage named CommunitiesLanding found"

### Additional information

You can get around it by creating a CommunitiesLandingController apex class and then the communitiesLandingPage, however, then you get an error because he urlPathPrefix isn't set up, etc, etc.  It seems that you need to create a community before you can deploy this file.

**Comment by pozil** [comment]
Hi @melissajhansen, I just went thought the process on a brand new Developer Edition org and couldn't reproduce this exact issue.

I just found and fixed another issue: the `siteGuestRecordDefaultOwner ` property needs to be updated with the current username in `E_Bikes.site-meta.xml` (step 8).

Can you make sure that you did not miss a step? I'm thinking about step 3 and 4 around community settings.

**Comment by melissajhansen** [comment]
@pozil I think I know what happened.  I have SFDX set to deploy-on-save, and I'm realizing that the instructions assume you're only editing the metadata file locally and then deploying all at once.  Derp.  Makes sense!!
