### ISSUE TITLE
Error in force-app/main/default/experiences/E_Bikes1.site-meta.xml

### ISSUE THREAD

**Issue by lbuthman** [trailheadapps/ebikes-lwc#184]
### Summary

After successfully completing the steps to setup the application in a scratch org as outlined in the README, I am unable to push code. It seems there is a compilation error in the xml definition for file E_Bikes1.site-meta.xml

### Steps To Reproduce:

1.  Follow steps to setup application.
2.  Create a new lwc component.
3.  run sfdx force:source:push -f

### Expected result

Local code would push into the scratch org without errors.

### Actual result

The operation fails. I can confirm this by opening force-app/main/default/experiences/E_Bikes1.site-meta.xml in VSCode and finding an error in the xml definition.

### Additional information

Error  force-app/main/default/experiences/E_Bikes1.site-meta.xml  An unexpected error occurred. Please include this ErrorId if you contact support: 1637429673-2611390 (1134033616)

**Comment by schandlergarcia** [comment]
Hello @lbuthman, I'm having trouble reproducing this in a scratch org. Can you confirm that Experience Bundle is activated in the scratch org? 

You can access that Under Community Management Settings > Enable ExperienceBundle Metadata API.

**Comment by lbuthman** [comment]
Hi @schandlergarcia, activating the Experience Bundle was the issue. It looks like that step is missing when setting up the Scratch org. I think I made an assumption that those steps were all that was required. If it is just me that made this mistake, then it's just me. Thanks for the help.
