### ISSUE TITLE
Not working on Scratch Org using Summer 20 Preview

### ISSUE THREAD

**Issue by enthuk** [trailheadapps/ebikes-lwc#195]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  Change the scratch org defn file to include "release" : "Preview",
1.  Push the repo clone to the scratch org

### Expected result

Installation complete

### Actual result

$ sfdx force:source:push
Job ID | 0Af2600000vjXJxCAM
SOURCE PROGRESS | ████████████████████████████████████████ | 87/88 Components
TYPE   PROJECT PATH                                               PROBLEM
─────  ─────────────────────────────────────────────────────────  ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error  force-app/main/default/experiences/E_Bikes1.site-meta.xml  An unexpected error occurred. Please include this ErrorId if you contact support: 123725729-61000 (1302355068)
ERROR running force:source:push:  Push failed.
### Additional information

_Feel free to attach a screenshot or code snippets_.

**Comment by schandlergarcia** [comment]
Hello @enthuk, 

We have had to make changes into e-bikes to be compatible with summer 20 release. These include changes like the flexipage metadata which would cause any pushes to fail. We have a blog coming out shortly that will give you a bit more detail, but for now feel free to take a look at those features.

https://github.com/trailheadapps/ebikes-lwc/tree/prerelease/summer20

Best
Stephan
