### ISSUE TITLE
Deploy error : Default_Navigation doesn't exist

### ISSUE THREAD

**Issue by mansijoshii** [trailheadapps/ebikes-lwc#199]
Followed the steps of ReadMe to deploy this app on a scratch org. But while doing an sfdx force:source:push, I get this error:

Error  force-app/main/default/experiences/E_Bikes1.site-meta.xml  We couldn't validate componentAttributes in E_Bikes1/themes/jepson.json for component f78b9665-bf73-45c3-b5e1-8bf378c0c8d4. Error: attribute [navigationMenuEditorRefresh]: The navigation menu Default_Navigation doesn’t exist.. Check your file and try again.

**Comment by mansijoshii** [comment]
If I remove the _"navigationMenuEditorRefresh": "Default_Navigation"_ component attribute, deploy works, but the metadata deploy operation fails with this component faliure:

Error  unpackaged/navigationMenus/Default_Navigation.navigationMenu  Default_Navigation  An unexpected error occurred. Please include this ErrorId if you contact support: 43989489-397799 (-1285520818)

**Comment by maccus-bo-wang** [comment]
Dear, 
When I ran the commnad of "sfdx force:source:deploy -p force-app", I got the errors in terms of "Error  force-app\main\default\experiences\E_Bikes1.site-meta.xml  An unexpected error occurred. Please include this ErrorId if you contact support: 2140272791-37716 (1302355068)".
How can I fix this error. hope to get you answer soon, thx in advance.

**Comment by pozil** [comment]
@maccus-bo-wang thanks for reporting this. This is a know issue, see #214.
We're working on it.

**Comment by pozil** [comment]
Issue fixed.
