### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by the1mattkaufman** [trailheadapps/ebikes-lwc#219]
**What is missing from the application? Please describe.**
the name of the primary branch of this repo is still set to master, which is no longer an acceptable standard.

**Describe the solution you'd like**
rename the master branch to main

**Describe alternatives you've considered**
None

**Additional context**
NA

**Comment by muenzpraeger** [comment]
Chainring the default branch is on the roadmap. It's just not as simple, as this will break existing stuff.

We are waiting [as per guidance from GitHub](https://github.com/github/renaming).
