### ISSUE TITLE
Step 8: Deploy Community metadata results in Error: "You can not create custom Guest profiles."

### ISSUE THREAD

**Issue by fzsfdc** [trailheadapps/ebikes-lwc#225]
### Summary
Following the GH steps: https://github.com/trailheadapps/ebikes-lwc for "Installing E-Bikes using a Scratch Org" and all successful until step 8. Deploy Community metadata: sfdx force:mdapi:deploy -d mdapiDeploy/unpackaged -w 5
Step 8: Deploy Community metadata results in Error: "You can not create custom Guest profiles."

### Steps To Reproduce:

1.  Step 1 -8 
1.  On Step 8: Deploy Community metadata results in Error: "You can not create custom Guest profiles."
=== Component Failures [1]
TYPE   FILE                                                  NAME             PROBLEM
─────  ────────────────────────────────────────────────────  ───────────────  ─────────────────────────────────────────
Error  unpackaged/profiles/E-Bikes Profile.profile-meta.xml  E-Bikes Profile  You can not create custom Guest profiles.

ERROR running force:mdapi:deploy:  The metadata deploy operation failed.

=> Looks like there is a challenge on line Profile.profile-meta.xml with
<userLicense>Guest</userLicense> since the Guest profile does not exist in a new Scratch Org.

### Expected result

MDAPI PROGRESS | ████████████████████████████████████████ | 4/4 Components
### Actual result

ERROR running force:mdapi:deploy:  The metadata deploy operation failed.

### Additional information

See screenshot
<img width="847" alt="Screenshot 2020-09-27 at 01 40 31" src="https://user-images.githubusercontent.com/61556763/94352277-21935c80-0063-11eb-8ec7-d0561258f04f.png">

**Comment by schandlergarcia** [comment]
Hello @fzsfdc - 

I've tried to reproduce this into a couple of org shapes but have had no luck. Can you confirm that you're not modifying `config/project-scratch-def.json` and that you are not trying to push into a prerelease org? 

Best
Stephan

**Comment by fzsfdc** [comment]
Issue resolved
