### ISSUE TITLE
Error deploying e-bikes toTrailhead Playground

### ISSUE THREAD

**Issue by weesvisje** [trailheadapps/ebikes-lwc#240]
### Summary

When deploying the e-bikes app to my Trailhead playground, I get the following error:

Error  force-app/main/default/prompts/OrderBuilder.prompt-meta.xml   No matching standard permission found: {!$Permission.StandardPermission.AccessWalkthroughs}
Error  force-app/main/default/prompts/ProductDetail.prompt-meta.xml  No matching standard permission found: {!$Permission.StandardPermission.AccessWalkthroughs}
Error  force-app/main/default/experiences/E_Bikes1.site-meta.xml     You have specified duplicate routes for the same application page in your bundle. Routes must be unique. Remove duplicates and try again. Product Family List, Product List
ERROR running force:source:deploy:  Deploy failed.

### Steps To Reproduce:

I followed steps 1 through 7 from https://github.com/trailheadapps/ebikes-lwc/blob/master/README.md#installing-e-bikes-using-a-developer-edition-org-or-a-trailhead-playground successfully.

### Expected result

App deployed

### Actual result

Deployment failed

### Additional information

-

**Comment by schandlergarcia** [comment]
Hello @weesvisje, 

Thanks for bringing this to our attention! There was an error with the In-App Guidance Walkthroughs that has now been corrected. 

I merged this into production in PR #241
