### ISSUE TITLE
Remove My Domain from setup instructions

### ISSUE THREAD

**Issue by pozil** [trailheadapps/ebikes-lwc#251]
My Domain is now auto activated in new DE orgs.<br/>Let's remove that step from install instructions.

**Comment by pozil** [comment]
This is fixed.

**Comment by jdrussett** [comment]
a question on this: the current README contains the following sub-point number 4 under point 4 of the Installing E-Bikes using a Developer Edition Org or a Trailhead Playground section: `Replace the value between the <subdomain> tags with your domain.` Does this mean providing the domain _name_, such as strange-moose-0wkudl-dev-ed, or the domain _URL_, which would be the same thing appended by .trailblaze.my.salesforce.com?

**Comment by pozil** [comment]
@jdrussett sorry for the delay, I missed this message on a closed issue.
You need to input the domain name and not the domain URL. I'll update the docs accordingly.
