### ISSUE TITLE
Error while deploying to dev org

### ISSUE THREAD

**Issue by bretondev** [trailheadapps/ebikes-lwc#286]
![Capture](https://user-images.githubusercontent.com/33033418/111522363-784c3a00-875a-11eb-81f8-0552a77dbb31.JPG)

**Comment by schandlergarcia** [comment]
Hello @bretondev, 
I've been unable to reproduce this in my environment - could you try these two things? 

1. Can you update the CLI and Plugins? https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_update_cli.htm
2. If that doesn't work - can you set the loglevel on the command? `--loglevel debug` and paste the result here? https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_dev_cli_log_messages.htm

Best
Stephan

**Comment by mkredaktor** [comment]
I have the same error, and I can't deploy app to my playground org

**Comment by mkredaktor** [comment]
It also happens with scratch org with command sfdx force:source:push

**Comment by schandlergarcia** [comment]
Hello @mkredaktor, 

I'm still unable to reproduce this - i've tried with a trailhead playground and a dev org again today. Just to verify, can you follow the steps mentioned above and supply the error response? 

Best
Stephan

**Comment by mkredaktor** [comment]
@schandlergarcia Hello,

Sure, I had done these two steps. I have last version of CLI. 

I've tried run commands sfdx force:source:push or update with --loglevel debug. And I always have the same issue like on screenshot from @bretondev

**Comment by pozil** [comment]
Hi all, I just saw a similar error reported by someone on Twitter.
This is a Salesforce CLI issue, check out the discussion here:
https://github.com/forcedotcom/cli/issues/860

**Comment by mkredaktor** [comment]
Oh. Thanks
