### ISSUE TITLE
Required ThemeLayouts are missing in the layouts section

### ISSUE THREAD

**Issue by gaelburneau** [trailheadapps/ebikes-lwc#313]
### Summary

Error when deploying.

### Steps To Reproduce:

1.  sfdx force:source:push on scratch org or sfdx force:source:deploy -p force-app on dev org

### Expected result

Deployment succeed.

### Actual result

`Error  force-app/main/default/experiences/E_Bikes1.site-meta.xml  Required ThemeLayouts are missing in the layouts section of E_Bikes1/themes/jepson.json. Add mappings for ServiceNotAvailable and try again.`

**Comment by sweidler** [comment]
Same issue for me

**Comment by Raj-160195** [comment]
I'm also facing the same issue

**Comment by pozil** [comment]
Hi all, thanks for reporting this issue. I have deployed a fix.
Please pull the latest version from the repo. You should now be able to deploy the app.
