### ISSUE TITLE
Your site needs a route with route type service-not-available. Update your file and try again.

### ISSUE THREAD

**Issue by gaelburneau** [trailheadapps/ebikes-lwc#315]
### Summary

Error when deploying.

### Steps To Reproduce:

1.  sfdx force:source:push on scratch org

### Expected result

Deployment succeed.

### Actual result

`Your site needs a route with route type service-not-available. Update your file and try again.`

**Comment by rodriggj** [comment]
![image](https://user-images.githubusercontent.com/8760590/123863710-2aada480-d8e7-11eb-8e3c-4896e65624aa.png)

**Comment by pozil** [comment]
Hi @gaelburneau  and @rodriggj. Sorry for not catching this while working on #313. It's crazy because I was able to deploy without this route and CI passed successfully on my last PR...
I just pushed a fix. Give it a try and let me know if something else is failing.

**Comment by gaelburneau** [comment]
> Hi @gaelburneau and @rodriggj. Sorry for not catching this while working on #313. It's crazy because I was able to deploy without this route and CI passed successfully on my last PR...
> I just pushed a fix. Give it a try and let me know if something else is failing.

It's ok now. Thanks a lot !
