### ISSUE TITLE
not able to clone the repository

### ISSUE THREAD

**Issue by isthiyaq** [trailheadapps/ebikes-lwc#323]
### Summary

i tried to clone the repository but its throwing the error

### Steps To Reproduce:

![image](https://user-images.githubusercontent.com/86550455/124379613-bbb0c100-dcd5-11eb-9be2-7ff6caf0765e.png)

### Expected result

clone successfully

### Actual result

_Describe what actually happened instead_.

### Additional information

![image](https://user-images.githubusercontent.com/86550455/124379629-d08d5480-dcd5-11eb-84e3-d801da57d4c5.png)

**Comment by isthiyaq** [comment]
Hi team can anyone of you please reply

**Comment by schandlergarcia** [comment]
Hello @isthiyaq - this seems to be an issue with your connection. Check out this stackexchange post for a solution: https://stackoverflow.com/questions/38618885/error-rpc-failed-curl-transfer-closed-with-outstanding-read-data-remaining
