### ISSUE TITLE
Security  Property 'enableSetPasswordInApi' not valid in version 52.0

### ISSUE THREAD

**Issue by b94901099** [trailheadapps/ebikes-lwc#324]
hi team, I followed the instruction and got an issue at the step creating scratch orgs 
sfdx force:org:create -s -f config/project-scratch-def.json -a ebikes
Error  shape/settings/Security.settings  Security  Property 'enableSetPasswordInApi' not valid in version 52.0
In my sfdx-project.json, I have this property "sourceApiVersion": "46.0"
Wonder how I can resolve this. 
Thanks in advance.

**Comment by b94901099** [comment]
I can successfully create the scratch org now but getting another issue deploying the Product__c object. 
Hope to get a solution here. 
Thanks 
```
$ sfdx force:org:create -s -f config/project-scratch-def.json -a ebikes
Successfully created scratch org: 00DR0000000MAVkMAO, username: test-nx8bo3thlimz@example.com
$ sfdx force:source:push
*** Deploying with SOAP ***
Job ID | 0AfR0000003xSMEKA2
SOURCE PROGRESS | ████████████████████████████████████████ | 91/92 Components
Error  force-app/main/default/objects/Case/fields/Product__c.field-meta.xml  Cannot update a field to a Lookup, MasterDetail, or Hierarchy from something else (44:13)
ERROR running force:source:push:  Push failed.
```

**Comment by b94901099** [comment]
thank you. I am not sure why product__c exist in the scratch org. it's a fresh org I just created before pushing the source.

**Comment by tggagne** [comment]
I'm getting the same problem.

> Error (ProblemDeployingSettings): A scratch org was created with username test-mu6slqkhoeoa@example.com, but the settings failed to deploy due to: 
> [Error] Security : Property 'enableSetPasswordInApi' not valid in version 60.0 

Is deleting Case.product__c really the solution to this error?  Should it be deleted in the production dev hub???
