### ISSUE TITLE
Use of planned deprecated Codecov version - needs update

### ISSUE THREAD

**Issue by dschach** [trailheadapps/ebikes-lwc#327]
### Summary

Codecov plans to deprecate v1 of their engine [https://about.codecov.io/blog/introducing-codecovs-new-uploader/](https://about.codecov.io/blog/introducing-codecovs-new-uploader/) and is currently advising use of version 2.0.1. All .yaml files using codecov should be updated to the new version.

Starting September 1, there will be random brown-outs of v1, and this repository should avoid those.

ALSO, there is a problem with how Codecov parses test result files generated in its workflow. A line is currently needed in the yaml file to delete one of the test result files. It does not affect the performance or output of the workflow. This may not be related directly to the version issue, but I have been advised by Codecov support to remove a test file

`Can you please delete all `'test-result-<ID NUMBER>.json'` files prior to upload? This should get you working for now while we work to add support for the new format.`

### Steps To Reproduce:

1.  This appears to happen on random repositories. It happened on one of mine and not the other. 
1.  Run the upload code as specified in the Codecov blog post, using v1 and not deleting the test result file.
1.  The job MAY hang as processing in Codecov web dashboard.

### Expected result

The code coverage for the project is updated. The badge is updated. The codecov job doesn't show as Processing.

### Actual result

The code coverage in the codecov dashboard shows no test data, and the badge on the repository readme does not show a percentage.

![Codecov Processing](https://user-images.githubusercontent.com/636977/126810419-69c14616-4df0-4c7a-9a8c-870f5ccbde34.png)

### Additional information

I would like to fork this code and update the workflow yaml files and submit a pull request. If I am unable to do so, I will add to this issue with specific updates to make to the workflow file so that someone else can do it.

**Comment by pozil** [comment]
Hi @dschach, thanks for the detailed explanation and PR. I'll look into this and make sure that we update all of our sample apps with this new version.

**Comment by pozil** [comment]
Fixed by #328
