### ISSUE TITLE
errors when pushing source

### ISSUE THREAD

**Issue by DeltaIndiana** [trailheadapps/ebikes-lwc#33]
Hi
I created the scratch org successfully but I get errors when doing the push:

force-app\main\default\flexipages\Account_Record_Page.flexipage-meta.xml  We couldn't retrieve the design time component information for component c:accountMap.
force-app\main\default\flexipages\Order_Record_Page.flexipage-meta.xml    We couldn't retrieve the design time component information for component c:productTileList.
force-app\main\default\flexipages\Product_Explorer.flexipage-meta.xml     We couldn't retrieve the design time component information for component c:productFilter.
force-app\main\default\flexipages\Product_Record_Page.flexipage-meta.xml  We couldn't retrieve the design time component information for component c:similarProducts.
force-app\main\default\tabs\Product_Explorer.tab-meta.xml                 In field: flexiPage - no FlexiPage named Product_Explorer found
force-app\main\default\applications\EBikes.app-meta.xmo CustomTab named Product_Explorer found
force-app\main\default\permissionsets\ebikes.permissioo CustomTab named Product_Explorer found
force-app\main\default\objects\Product__c\Product__c.oge does not exist or is not a valid override for actioforce-app\main\default\objects\Account\Account.object-ge does not exist or is not a valid override for actioforce-app\main\default\objects\Order__c\Order__c.objec does not exist or is not a valid override for action

Can you help me please?

**Comment by muenzpraeger** [comment]
It looks like that you're not running Salesforce CLI in the current version.

Run `sfdx plugins --core`. The version of the `salesforcedx` plugin should be `45.xx`. If that's not the case update the plugin with `sfdx plugins:install salesforcedx@latest`.

**Comment by DeltaIndiana** [comment]
Yes that was the issue. Thank you for your prompt reply.
