### ISSUE TITLE
Invalid reference Product__c of type sobjectClass

### ISSUE THREAD

**Issue by yeryndo** [trailheadapps/ebikes-lwc#337]
### Summary

Not able to see Product Card component in Lightning App Builder

### Steps To Reproduce:

1. Copied bikeCard.js-meta.xml code:
<?xml version="1.0" encoding="UTF-8" ?>
<LightningComponentBundle xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>52.0</apiVersion>
    <isExposed>true</isExposed>
    <masterLabel>Product Card</masterLabel>
    <targets>
        <target>lightning__AppPage</target>
        <target>lightning__RecordPage</target>
        <target>lightning__HomePage</target>
        <target>lightningCommunity__Page</target>
    </targets>
    <targetConfigs>
        <targetConfig targets="lightning__RecordPage">
            <objects>
                <object>Product__c</object>
            </objects>
        </targetConfig>
    </targetConfigs>
</LightningComponentBundle>
2. Ran SFDX: Deploy Source to org

### Expected result

Should have been able to deploy source to org

### Actual result
Cannot deploy source to org

14:56:14.82 Starting SFDX: Deploy Source to Org

=== Deploy Errors
PROJECT PATH  ERRORS                                                                        
────────────  ──────────────────────────────────────────────────────────────────────────────
              Invalid reference Product__c of type sobjectClass in file bikeCard.js-meta.xml

14:56:17.874 ended SFDX: Deploy Source to Org

**Comment by TobiasDiaz1** [comment]
The only way I was able to complete this part of the module was by removing this portion:

<targetConfigs>
        <targetConfig targets="lightning__RecordPage">
            <objects>
                <object>Product__c</object>
            </objects>
        </targetConfig>
    </targetConfigs>
   
The challenge itself doesn't check for whatever this is supposed to do. ^

Also, the challenge doesn't say to copy the second meta.xml that you see, but is only showing you an EXAMPLE of what the file looks like from a different repo, though it'd be nice if the code used was different.

I just finished the challenge myself without needing it.

**Comment by nawazzz** [comment]
The api version in the XML file should match the api version in sfdx-project.json

**Comment by parmardeep27061997** [comment]
> The only way I was able to complete this part of the module was by removing this portion:
> 
> Product__c
> The challenge itself doesn't check for whatever this is supposed to do. ^
> 
> Also, the challenge doesn't say to copy the second meta.xml that you see, but is only showing you an EXAMPLE of what the file looks like from a different repo, though it'd be nice if the code used was different.
> 
> I just finished the challenge myself without needing it.

Helpfull...
