### ISSUE TITLE
sfdx-project.json issue

### ISSUE THREAD

**Issue by jared201** [trailheadapps/ebikes-lwc#34]
I'm getting this issue while authorising a playground/org

`All JSON input must have heads down camelcase keys. E.g., { sfdcLoginUrl: "https://login.salesforce.com" } Found "EBikesLWC" at /Users/jared/ebikes-lwc/sfdx-project.json`

**Comment by muenzpraeger** [comment]
It's a known issue with the CLI which will be fixed soon. Meanwhile you can change, by hand, the alias that's mentioned to "eBikes" to prevent the warning.

**Comment by PawelWozniak** [comment]
I have got it too doing trailhead module https://trailhead.salesforce.com/content/learn/modules/lightning-web-components-basics/push-lightning-web-component-files?trailmix_creator_id=strailhead&trailmix_id=lightning-web-components

**Comment by vleandro** [comment]
I fixed this by modifying the sfdx-project.json.  Change the "package" name from "EBikesLWC" to "eBikesLWC".  Do the same for the two referenced packageAliases.
