### ISSUE TITLE
Data import seems broken

### ISSUE THREAD

**Issue by ibigfoot** [trailheadapps/ebikes-lwc#38]
### Summary

when running the data import, receive this error ..

`>sfdx force:data:tree:import --plan ./data/sample-data-plan.json 

ERROR running force:data:tree:import:  ENOENT: no such file or directory, open '/usr/local/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/schemas/dataImportPlanSchema.json'
tsellers-ltm3:ebikes-lwc tsellers$ `

### Steps To Reproduce:

1.  Install CLI via NPM
1.  Clone git repo and follow the install steps

**Comment by muenzpraeger** [comment]
Thanks for reporting this @ibigfoot. That's a CLI issue, not associated to this repo. A patch for that should go out within the next 30 minutes.

**Comment by yjanezou** [comment]
@muenzpraeger I am also getting this error. Could you tell me how to fix it?

**Comment by muenzpraeger** [comment]
Run `sfdx update`.

**Comment by CherukuriVinod** [comment]
I used this command to import sample data for ebike. sfdx force:data:tree:import -p ./data/sample-data-plan.json

Error I am receiving.
ERROR running force:data:tree:import:  {"hasErrors":true,"results":[{"referenceId":"AccountRef1","errors":[{"statusCode":"DUPLICATES_DETECTED","message":"Use one of these records?","fields":[]}]},{"referenceId":"AccountRef2","errors":[{"statusCode":"DUPLICATES_DETECTED","message":"Use one of these records?","fields":[]}]},{"referenceId":"AccountRef3","errors":[{"statusCode":"DUPLICATES_DETECTED","message":"Use one of these records?","fields":[]}]}]}

**Comment by nmnzaki** [comment]
> I used this command to import sample data for ebike. sfdx force:data:tree:import -p ./data/sample-data-plan.json
> 
> I am also getting the same error. Can anyone  help me with it? 
ERROR running force:data:tree:import: {"hasErrors":true,"results":[{"referenceId":"AccountRef1","errors":[{"statusCode":"DUPLICATES_DETECTED","message":"Use one of these records?","fields":[]}]},{"referenceId":"AccountRef2","errors":[{"statusCode":"DUPLICATES_DETECTED","message":"Use one of these records?","fields":[]}]},{"referenceId":"AccountRef3","errors":[{"statusCode":"DUPLICATES_DETECTED","message":"Use one of these records?","fields":[]}]}]}

**Comment by pratikshambharkar1999** [comment]
Go to **Devloper Console** 
**Query** :- select id, name from account where lastModifiedDate >=today
you will get the below three account and **delete them**

![image](https://user-images.githubusercontent.com/97441127/151303634-6d06414f-ea07-467a-8883-4dc4cd84c3fa.png)

after deleting those account go to VS code and execute the command

sfdx force:data:tree:import --plan ./data/sample-data-plan.json

![image](https://user-images.githubusercontent.com/97441127/151304058-aa6a19ae-db60-4dbf-b251-8737be7eb928.png)
