### ISSUE TITLE
Error on running command - sfdx force:mdapi:deploy -d guest-profile-metadata -w 10

### ISSUE THREAD

**Issue by rb-sfdc** [trailheadapps/ebikes-lwc#391]
### Summary

Previous commands were successful, but after running the below command, getting error

PS C:\Ruchika\Demo_CGI\Recipe_Ebike\ebikes-lwc> sfdx force:mdapi:deploy -d guest-profile-metadata -w 10
*** Deploying with SOAP ***
Job ID | 0Af5j00000D0QRFCA3
MDAPI PROGRESS | ██████████████████████████████████░░░░░░ | 6/7 Components

=== Component Failures [1]
TYPE   FILE                                                     NAME             PROBLEM─────  
Error  guest-profile-metadata/profiles/E-Bikes Profile.profile  E-Bikes Profile  In field: field - no CustomField named Case.AssetWarrantyId found

ERROR running force:mdapi:deploy:  The metadata deploy operation failed.

### Salesforce Org Type

Trailhead Playground

### Steps To Reproduce

Installing the steps using steps mentioned in : https://github.com/trailheadapps/ebikes-lwc
Run command 
sfdx force:mdapi:deploy -d guest-profile-metadata -w 10

Error found
Error  guest-profile-metadata/profiles/E-Bikes Profile.profile  E-Bikes Profile  In field: field - no CustomField named Case.AssetWarrantyId found

ERROR running force:mdapi:deploy:  The metadata deploy operation failed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by schandlergarcia** [comment]
Hello @rb-sfdc - this has been resolved with the latest PR #392
