### ISSUE TITLE
Error during `npm install` execution

### ISSUE THREAD

**Issue by jmsfez** [trailheadapps/ebikes-lwc#40]
### Summary

I succeed to follow instructions for Installing **E-Bikes using a Scratch Org**.
However, I have an error when I try to install the optional **Pre-commit hook** .
More precisely, when running the `npm install` command, I get the following error:
![image](https://user-images.githubusercontent.com/28300202/56080288-67248100-5dff-11e9-963a-295a7c450967.png)

### Steps To Reproduce:

I follow the instructions for **E-Bikes using a Scratch Org**:
$ git clone https://github.com/trailheadapps/ebikes-lwc
$ cd ebikes-lwc/
$ sfdx force:org:delete -u ebikes
$  sfdx force:org:create -s -f config/project-scratch-def.json -a ebikes
$  sfdx force:source:push
$  sfdx force:user:permset:assign -n ebikes
$  sfdx force:data:tree:import --plan ./data/sample-data-plan.json
$  sfdx force:org:open

Then, I installed the Prettier extension for Visual Studio Code.
I already have the Lightning Web Component extension for Visual Studio Code.
Then I installed node.js version 10.15.3.
And I ran the command
**$  npm install**

### Expected result

Probably a « success message »

### Actual result

An « error message »:
```
$ npm install

> deasync@0.1.12 install /Users/jsfez/dev/ebikes-lwc/node_modules/deasync
> node ./build.js

gyp ERR! configure error
gyp ERR! stack Error: Command failed: /anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
gyp ERR! stack     at Socket.emit (events.js:189:13)
gyp ERR! stack     at Pipe._handle.close (net.js:597:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jsfez/dev/ebikes-lwc/node_modules/deasync
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.12 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jsfez/.npm/_logs/2019-04-13T13_14_18_402Z-debug.log
```

### Additional information

I'm working on Mac OS X

**Comment by muenzpraeger** [comment]
Please checkout the documentation for `lwc-jest`. That one points out how to fix the `deasync` error.

https://github.com/salesforce/lwc-jest/blob/master/README.md#troubleshooting-deasync-installation-errors

I’ll update the readme here also to link to that. Thanks for pointing it out.

**Comment by jmsfez** [comment]
Ok, I still have an issue by following what they said but I open an issue their.
Thanks for your support ;)
