### ISSUE TITLE
Error during `sfdx force:source:deploy -p force-app -u ${ORG}`

### ISSUE THREAD

**Issue by jmsfez** [trailheadapps/ebikes-lwc#41]
### Summary

It seems impossible to deploy the application to a Trailhead Playground because the Lightning Bundle name 'pageTemplate_2_7_3' is already defined.
I succeed to deploy only after removing the `pageTemplate_2_7_3/` directory from the `./force-app/main/default/aura`.
May be you should remove it from the GitHub repository.

**Comment by muenzpraeger** [comment]
What’s the error that you get? And is the Trailhead Playground empty, or did you deploy any other metadata before into it?

**Comment by jmsfez** [comment]
I didn't create a screen copy but it was saying that `pageTemplate_2_7_3` is already defined.
The Trailhead Playground was not empty, I made many Trailhead modules in it.
I just create a new empty Trailhead Playground and it does not contain that page template.
So you've right, I probably get the page template from a previous Trailhead module ;)
May be you can just includes a comment to explain that this page template can be removed in case it already exist in the org.
Thanks for you time ;)

**Comment by jmsfez** [comment]
Here is the exact message:

![image](https://user-images.githubusercontent.com/28300202/56094957-1f255d00-5ed8-11e9-94c1-bf4a00e0f4d5.png)
