### ISSUE TITLE
productTileList.js duplicate declaration of `products` property

### ISSUE THREAD

**Issue by douglascayers** [trailheadapps/ebikes-lwc#45]
### Summary

The `productTileList.js` class declares the property `products` twice, once decorated with `@track` and initialized to empty array, and then later decorated with `@wire` and initialized as null (until the wire action executes).

![image](https://user-images.githubusercontent.com/4142577/57595093-d679b780-7508-11e9-931f-bbdca73c5550.png)

This leads to ambiguous behavior of what the initial value of `products` property will be. Looking at the code, it feels like the developer is intending to default to an empty array but because the first declaration is overridden later then the property is actually initialized as null.

Using Chrome Dev Tools, you can inspect the source of the productTileList.js file and see the duplicate declaration:

![image](https://user-images.githubusercontent.com/4142577/57595163-18a2f900-7509-11e9-8cb9-734488e3a341.png)

### Expected result

Declare properties exactly once in the JavaScript class.

In this case, delete the lines:
```
    /** All available Product__c[]. */
    @track products = [];
```

**Comment by muenzpraeger** [comment]
Fixed with #47, will be shipped with the Summer '19 release update
