### ISSUE TITLE
Cannot push source to the org

### ISSUE THREAD

**Issue by ruwanthalk** [trailheadapps/ebikes-lwc#454]
### Summary

I am trying to push the freshly created code to org and I am getting the following error when I try to push the source as instructed in the md file.

![image](https://user-images.githubusercontent.com/8010368/182443291-da93f353-3115-4028-acf7-2a227ce24c3d.png)

### Salesforce Org Type

Scratch Org

### Steps To Reproduce

1. create a fork 
2. follow all the instruction in the MD file
3.  at step 5 above given error will happeninstructions

### Current Behavior

Unable to deploy the sample code easily to the org

### Expected Behavior

Should be able to push the source to the org with  sfdx

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pozil** [comment]
Hi @ruwanthalk, are you really using a scratch org or have you changed the scratch org configuration?
Scratch orgs have the CEO user role by default so I'm a bit puzzled.

**Comment by ruwanthalk** [comment]
@pozil you are correct. Closing the issue
