### ISSUE TITLE
Unable to import the sample data

### ISSUE THREAD

**Issue by Harshit-Saxena** [trailheadapps/ebikes-lwc#455]
### Summary

![Screenshot 2022-07-31 at 9 42 13 PM](https://user-images.githubusercontent.com/18752758/182792133-4113a6f0-dca2-4908-acc4-2dd5a2946567.png)
 
- Following the .md file 
> sfdx force:data:tree:import --plan ./data/sample-data-plan.json 

### Salesforce Org Type

Developer Edition Org

### Steps To Reproduce

1 . Developer edition
2. code is deployed but no products are begin displayed by the sample app 
3. ![Screenshot 2022-08-04 at 1 15 12 PM](https://user-images.githubusercontent.com/18752758/182792693-7a018070-269b-4129-80a6-bdf97f0947c7.png)

 

### Current Behavior

I wanted to import the sample data provided in the repository itself, but it's showing duplicate records in a newly fresh org.  

### Expected Behavior

It should finish the importing the sample data. 
> ./data/sample-data-plan.json      

### Relevant Log Output

```shell
sfdx force:data:tree:import --plan ./data/sample-data-plan.json
ERROR running force:data:tree:import:  {"hasErrors":true,"results":[{"referenceId":"AccountRef1","errors":[{"statusCode":"DUPLICATES_DETECTED","message":"Use one of these records?","fields":[]}]},{"referenceId":"AccountRef2","errors":[{"statusCode":"DUPLICATES_DETECTED","message":"Use one of these records?","fields":[]}]},{"referenceId":"AccountRef3","errors":[{"statusCode":"DUPLICATES_DETECTED","message":"Use one of these records?","fields":[]}]}]}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pozil** [comment]
Hi @Harshit-Saxena, according to the error message, all of the accounts (not products) that are referenced in the data plan already exist in your org. Can you double check the accounts that are in your org?

**Comment by Harshit-Saxena** [comment]
Hello @pozil, There are some accounts, but how can I check for the associations?

![Screenshot 2022-08-04 at 5 06 46 PM](https://user-images.githubusercontent.com/18752758/182838056-44dd62cd-e705-4abd-93b1-6fad46d9cbd7.png)

![Screenshot 2022-08-04 at 5 06 23 PM](https://user-images.githubusercontent.com/18752758/182838066-ec2e66c3-a421-4572-a1fb-410deb21c844.png)

**Comment by pozil** [comment]
The three last ones in your Developer Console screenshot are the ones that are included in the sample app [data plan](https://github.com/trailheadapps/ebikes-lwc/blob/main/data/Accounts.json). This is why you have a conflict.
Remove them and try again to import the sample data.

**Comment by Harshit-Saxena** [comment]
It worked I had to delete the last four accounts and then the products are imported. 

![Screenshot 2022-08-04 at 5 56 42 PM](https://user-images.githubusercontent.com/18752758/182846788-46172901-7513-4d68-b401-fbd7069a1c49.png)
