### ISSUE TITLE
Winter '23 deployment issue

### ISSUE THREAD

**Issue by mythili16** [trailheadapps/ebikes-lwc#458]
### Summary

I am trying to Install E-Bikes using a Developer Edition Org, when I run this command
`sfdx force:mdapi:deploy -d guest-profile-metadata -w 10`

I am getting the below error:

Error parsing file: Element {http://soap.sforce.com/2006/04/metadata}fieldPermissions invalid at this location in type ProfileFieldLevelSecurity

### Salesforce Org Type

Developer Edition Org

### Relevant Log Output

```shell
=== Component Failures [1]

 Type  File                                 Name            Problem                                                                                                         
 ───── ──────────────────────────────────── ─────────────── ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 Error zip/profiles/E-Bikes Profile.profile E-Bikes Profile Error parsing file: Element {http://soap.sforce.com/2006/04/metadata}fieldPermissions invalid at this location in type ProfileFieldLevelSecurity

ERROR running force:mdapi:deploy:  The metadata deploy operation failed.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pozil** [comment]
HI @mythili16, if you tried to deploy the app on a Winter '23 org, then this is normal. We haven't updated the app to API v56.0 yet. We will do that for the Salesforce release. Try again starting from Oct 17.

**Comment by pozil** [comment]
Addressed in #461

**Comment by mythili16** [comment]
@pozil Is the issue fixed?

**Comment by mythili16** [comment]
@pozil I'm able to successfully deploy the app in winter '22 org. Before deploying, I had to delete a few field permissions from profiles/E-Bikes Profile.profile as these custom fields don't exist in the app --> Case.EntitlementId, Case.IsStopped, Case.MilestoneStatus, Case.MilestoneStatusIcon, Case.ProductId, Case.ServiceContractId, Case.SlaExitDate, Case.SlaStartDate, Case.StopStartDate. Please do changes in the repo as well. Thank you!
