### ISSUE TITLE
Product Filter Component

### ISSUE THREAD

**Issue by ekowkaay** [trailheadapps/ebikes-lwc#464]
I would like to find out if there is a way to show 10 picklist values for the Category Filter if you have for example 20 values to display with a dropdown which displays the rest of the values once you click on it.

**Comment by pozil** [comment]
Hi @ekowkaay, we don't have such an example in our apps but I don't see why you couldn't implement this behavior if you needed to.

**Comment by ekowkaay** [comment]
Oh, okay. Thanks.

Regards,

Emmanuel
