### ISSUE TITLE
Unable to deploy to dev sb.

### ISSUE THREAD

**Issue by lmbugua852** [trailheadapps/ebikes-lwc#542]
### Summary

![image](https://github.com/trailheadapps/ebikes-lwc/assets/4401650/953a7edc-7a6d-4542-b0bb-66223ed243a1)

### Salesforce Org Type

Developer Edition Org

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pozil** [comment]
Hi @lmbugua852 thanks for opening an issue.
I did a full deploy following the instructions but I wasn't able to reproduce the issue.
I have a couple of questions to try to help:
1. are you trying to deploy on a Summer '23 pre-release org? If yes, you need to use the content form the `prerelease/summer23` branch.
1. did you apply step 5 from the instructions?
    > Remove the Product custom field from the Case object

**Comment by pozil** [comment]
Looking at your output, this is clearly a Spring '23 org (API v57.0) so the prerelease branch won't work (as expected).

Sorry to ask but could you try to deploy from `main` on a Trailhead Playground org?

**Comment by lmbugua852** [comment]
![image](https://github.com/trailheadapps/ebikes-lwc/assets/4401650/4aa1319a-bab6-45a2-a1f8-27650c058328)

No issues with a new trailhead org. Thanks Pozil!
