### ISSUE TITLE
Error - This site already includes a menu called Default Navigation. Enter a unique name.

### ISSUE THREAD

**Issue by salesforcejourney** [trailheadapps/ebikes-lwc#545]
### Summary

While deploying EBike on my dev org, I am getting below error.

| Error E_Bikes1           We couldn't validate componentAttributes in E_Bikes1/themes/jepson.json for component f78b9…
| Error Default_Navigation This site already includes a menu called Default Navigation. Enter a unique name.

### Salesforce Org Type

Developer Edition Org

### Steps To Reproduce

Follow the steps as mentioned in below link

https://github.com/trailheadapps/ebikes-lwc

### Current Behavior

Deployment failing with below error

Component Failures [2]
=======================================================================================================================
| Type  Name               Problem
| ───── ────────────────── ────────────────────────────────────────────────────────────────────────────────────────────
| Error E_Bikes1           We couldn't validate componentAttributes in E_Bikes1/themes/jepson.json for component f78b9…
| Error Default_Navigation This site already includes a menu called Default Navigation. Enter a unique name.

### Relevant Log Output

```shell
C:\Users\ankit\OneDrive\Desktop\VS Code Projects\ebikes-lwc>sf org login web -s -a mydevorg
 »   Warning: @salesforce/cli update available from 1.80.0 to 1.83.4.
Successfully authorized khiwansaracrm@gmail.com with org ID 00D5j000001wdJ6EAI

C:\Users\ankit\OneDrive\Desktop\VS Code Projects\ebikes-lwc>sf project deploy start -d force-app
 »   Warning: @salesforce/cli update available from 1.80.0 to 1.83.4.
*** Deploying with SOAP API v58.0 ***
Deploy ID: 0Af5j00000QMVoeCAH
Status: Failed | ████████████████████████████████████████ | 100/100 Components

Component Failures [2]
=======================================================================================================================
| Type  Name               Problem
| ───── ────────────────── ────────────────────────────────────────────────────────────────────────────────────────────
| Error E_Bikes1           We couldn't validate componentAttributes in E_Bikes1/themes/jepson.json for component f78b9…
| Error Default_Navigation This site already includes a menu called Default Navigation. Enter a unique name.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pozil** [comment]
Hi sorry for the delay in my response. I ran the entire setup instructions with a new dev org and wasn't able to reproduce the issue.
`Default_Navigation` errors may occur when installing on non empty orgs. Were you using a clean org?
