### ISSUE TITLE
Can't import data

### ISSUE THREAD

**Issue by himlayyy** [trailheadapps/ebikes-lwc#561]
### Summary

After installing the app, I tried importing data following the instructions but I got this error: 

We couldn't process your request because you don't have access to Description__c on Product_Family__c. To learn more about field-level security,
 visit Tips and Hints for Page Layouts and Field-Level Security in our Developer Documentation.
<img width="701" alt="image" src="https://github.com/trailheadapps/ebikes-lwc/assets/24460065/0b5a9190-ea2e-4e98-93fd-f663f0f9d6d1">

### Salesforce Org Type

Trailhead Playground

### Steps To Reproduce

sf project deploy start -d force-app
sf data tree import -p ./data/sample-data-plan.json

### Expected Behavior

I should be able to import data

### Relevant Log Output

```shell
Error (1): We couldn't process your request because you don't have access to Description__c on Product_Family__c. To learn more about field-level security, visit Tips and Hints for Page Layouts and Field-Level Security in our Developer Documentation.
PS C:\Users\alesandra.mae.lelis\Bootcamp Activity\ebikes-lwc>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pozil** [comment]
Hi @himlayyy, can you make sure that you have assigned the correct permission set to your user as per the readme instructions?
