### ISSUE TITLE
Product Explorer does not refresh

### ISSUE THREAD

**Issue by beppealf** [trailheadapps/ebikes-lwc#57]
### Summary

_Product Exporer does not refresh_.

### Steps To Reproduce:

1.  Fresh install of ebikes in a scratch org.
2.  Go to Product Explorer tab.
3.  Deselect a check box in Filters (i.e. Aluminium).
4.  Nothing happens.
5.  Refresh the browser with F5.
6.  Wait 6 minutes.
7.  Deselect a check box in Filters (i.e. Aluminium).
8.  Product Tile List get refreshed and show less products.

### Expected result

_Product Tile List shoud have refreshed_.

### Actual result

_Product Tile List did not refresh_.

### Additional information

_It seems that events in Filters are not processed, They get processed only if I do a click every 6 minutes or so_.

**Comment by muenzpraeger** [comment]
Thanks for reporting, @beppealf. This looks like an issue with the `@wire` adapter. I've forwarded this internally.

**Comment by rendall** [comment]
This might help, as it's related to the `@wire` adapter. 

I'm not able to see Product Explorer at all with a new install. When I open that page in Community Builder preview, I get this error:
```
This page has an error. You might just need to refresh it. 
afterRender threw an error in 'c:productTileList' 
[pubsub listeners need a "@wire(CurrentPageReference) pageRef" property] 
Failing descriptor: {c:productTileList}
```

**Comment by beppealf** [comment]
For community related issues it seems that the CurrentPageReference issue has not yet been solved.

I managed to make it work this way (adjusted some permissions as well for public viewing) 

See here https://salesforce.stackexchange.com/questions/252021/lightning-web-component-use-publish-subscribe-event-in-community-cloud

This was done as well in the now unfortunately archived 

https://github.com/trailheadapps/ebikes-communities-lwc/blob/master/force-app/main/default/lwc/pubsub/pubsub.js

**Comment by muenzpraeger** [comment]
There are multiple, non-related items in this thread:

@beppealf The refresh of `wire` within Lightning Experience is investigated. It's not related to Communities.

@rendall This is specific only to Communities, and only in the Builder view.

The solution that @beppealf pointed out was a workaround, which _should_ be obsolete now, and it relates to using Product Explorer/pubsub in Communities, not Builder. At the same time keeping in mind that `pubsub.js` was originally developed for Lightning Experience only.

**Comment by JigarLakhaniAtJade** [comment]
Hi,

I am getting the same issue, It is not refreshing while entering some value to search or selecting any checkbox from filters.

Can you please help?

Thank you

**Comment by fabricepierre** [comment]
> Thanks for reporting, @beppealf. This looks like an issue with the `@wire` adapter. I've forwarded this internally.

@muenzpraeger , Do you have an update in relation to this issue? Any known issue we could subscribe too?

**Comment by kevinv11n** [comment]
We're working on a fix. Should go out in the next couple patches #safeharbor. Bug id is W-6340254.

**Comment by amitkumarj1979** [comment]
Could not find the bug on Known Issues site. Any ETA on when the fix will be pushed ?

**Comment by muenzpraeger** [comment]
Fix is in production. Closing this issue now.
