### ISSUE TITLE
Unable to deploy to Trailhead Playground Org

### ISSUE THREAD

**Issue by chris-wilkinson-81** [trailheadapps/ebikes-lwc#58]
### Summary

Hello, I'm trying to deploy this package to my Trailhead Org here:
https://playful-moose-qpozcr-dev-ed.lightning.force.com/

After following the deployment steps in the ReadMe, I used the following command to deploy the package to my org:
sfdx force:source:deploy -p force-app -u chris.wilkinson@playful-moose-qpozcr.com --verbose

However, I'm getting the following 8 errors when I deploy the package:

1. Error  sdx_sourceDeploy_1561407841240/objects/Account.object                     Account.All_Acounts                     SharedTo not allowed:roleAndSubordinatesInternal - CEO
2. Error  sdx_sourceDeploy_1561407841240/layouts/Case-Case Layout.layout            Case-Case Layout                        In field: QuickAction - no QuickAction named Case.CaseComment found
3. Error  sdx_sourceDeploy_1561407841240/objects/Case.object                        Case.Product__c                         Cannot update a field to a Lookup, MasterDetail, or Hierarchy from something else
4. Error  sdx_sourceDeploy_1561407841240/networkBranding/cbE_Bikes.networkBranding  cbE_Bikes                               Network not found for the CustomBrand : cbE_Bikes
5. Error  sdx_sourceDeploy_1561407841240/networks/E-Bikes.network                   E-Bikes                                 Not available for deploy for this organization
6. Error  sdx_sourceDeploy_1561407841240/sites/E_Bikes.site                         E_Bikes                                 Communities must be enabled before deploying a Chatter Network Site
7. Error  sdx_sourceDeploy_1561407841240/siteDotComSites/E_Bikes_C.site             E_Bikes_C                               You don't have the correct site publisher privileges for this operation Site : E-Bikes, type: Site.com Community(db=C,api=ChatterNetworkPicasso)
8. Error  sdx_sourceDeploy_1561407841240/objects/Product_Family__c.object           Product_Family__c.All_Product_Families  SharedTo not allowed:roleAndSubordinatesInternal - CEO

### Steps To Reproduce:

Clone the repository and follow the installation instructions in the readme for a Trailhead Org.

### Expected result

The package deploys to my org

### Actual result

SFDX deployment fails with the 8 errors noted above

### Additional information

Has this package been validated with Summer 2019 release?

**Comment by muenzpraeger** [comment]
Is this an existing Playground, or one where you had already modifications in?

**Comment by chris-wilkinson-81** [comment]
Hi,

I tried two Playground Orgs, one with may of my other Badge customizations and one that was brand new.  I got the same 8 errors on both orgs.

Thanks for your quick reply,

Chris

**Comment by muenzpraeger** [comment]
Sure thing. I’ll validate ASAP (late here in Germany), and come back to this.

**Comment by muenzpraeger** [comment]
@chris-wilkinson-81 I just checked. There are the steps `3` and `4` in the README that guide you through activating Communities and remove an existent field. That should fix your issue.

**Comment by chris-wilkinson-81** [comment]
@muenzpraeger - you were correct, I needed to follow the steps under the Installing **E-Bikes using a Developer Edition Org** section.  I didn't understand that,  I thought my Trailhead Playground as a different type of Org.

Thanks for your help.

Chris

**Comment by cozyxin** [comment]
Hi, I have another problem when deploying to the Developer Edition Org.
![image](https://user-images.githubusercontent.com/34984218/63555343-d8312d80-c583-11e9-81f2-ffaede4d6174.png)
I am not sure if it is related to E_Bikes.site-meta.xml <subdomain> value, this is my local file config.
![image](https://user-images.githubusercontent.com/34984218/63555390-07e03580-c584-11e9-8e7a-778beae0f30a.png)
And this is my community settings:
![image](https://user-images.githubusercontent.com/34984218/63556551-ae2e3a00-c588-11e9-8991-f0e599baa6c5.png)

I have tried ebikes, lunawen, lunawen-developer-edition.ap15.force.com for the subdomain values, but nothing works, the deploy command always gives the same error message.

Please help, stuck for more than 3 hours.

**Comment by muenzpraeger** [comment]
You likely have already an Aura component in your org with the name `paginator`.
