### ISSUE TITLE
Navigated to invalid page when "See Electra Bikes" button where it is located on the home page is clicked

### ISSUE THREAD

**Issue by oguzhancvdr** [trailheadapps/ebikes-lwc#584]
### Summary

Hello, When I practice with lwc via [Quick Start: Explore the E-Bikes Sample App](https://trailhead.salesforce.com/content/learn/projects/quick-start-ebikes-sample-app?trail_id=discover-trailhead-sample-apps), I have realized that "see electra bikes" button navigates me to invalid page. Thus, I report this small bug and contribute to this helpful repo.

### Salesforce Org Type

Scratch Org

### Steps To Reproduce

1. Login into your salesforce org which is E-Bikes, experience site, is deployed and published.
2. In Setup, write all sites in Quick Find search bar and click All Sites under the Digital Experiences
3. There will be your sites, Find the site which is named as E-Bikes and click the url which is under the URL column.
4. After you open the e-bike site, click the SEE ELECTRA BIKES button which is located on second banner.
5. You will be navigated to invalid page.

### Current Behavior

The "see electra bikes" button where it is located on the second banner of the home page leads to invalid page. The related wrong path is "ebikes/s/product-family/a028e000004Ls1wAAC"

### Expected Behavior

The "see electra bikes" button where it is located on the second banner of the home page should navigate to details page not to the product-family page. The path should be changed from "ebikes/s/**product-family**/a028e000004Ls1wAAC" to "ebikes/s/**detail**/a028e000004Ls1wAAC".

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pozil** [comment]
Thanks for the fix. I merged your PR.
