### ISSUE TITLE
How to Hide Products Already Added to Orders

### ISSUE THREAD

**Issue by efortenberry** [trailheadapps/ebikes-lwc#59]
Hello, thanks for this great application!  I've been using this code to create an Order Builder in my org and I was hoping you could help me understand how I could modify the code so that after I drag and drop a productTile on to the order, that ProductTile could be removed from the ProductTileList?  Said another way, I only want to show Products that are not already added to the Order?

Thanks for pointing me in the right direction!  This is my first time working with lwc.

**Comment by muenzpraeger** [comment]
Sorry for the late reply.

The `productTileList` is driven by data from the `getProducts` method in Apex. You can "remove" the selected product by storing the result not in the `products` property, but in a dedicated variable lets say `unselectedProducts`. That way you can manipulate the items of `unselectedProducts` (aka: remove an element) once the product got dropped onto the order.
