### ISSUE TITLE
Problems with flexi-pages

### ISSUE THREAD

**Issue by deb761** [trailheadapps/ebikes-lwc#60]
I'm getting an error when attempting to push the sfdx project to a scratch org:

1. Cloned ebike-lwc
1. Created a new lwc according to Trailhead module
1. ran `sfdx force:source:push`

Got the following errors:

   1. Order_Record_Page.flexipage-meta.xml: 
We couldn't retrieve the design time component information for component c:productTileList.

   1. Product_Explorer.flexipage-meta.xml: We couldn't retrieve the design time component information for component c:productFilter.

`sfdx plugins --core
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.2.0 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.1.2 (core)
generator 1.1.0 (core)
salesforcedx 46.3.0
├─ force-language-services 46.8.0
└─ salesforce-alm 46.7.0

sfdx-cli 7.12.3 (core)`

**Comment by muenzpraeger** [comment]
Can you provide more information in which context this error appears, @deb761? Thanks!

**Comment by deb761** [comment]
Sorry about that - updated the issue.

**Comment by muenzpraeger** [comment]
Cannot be reproduced.
