### ISSUE TITLE
README Step 6 Failure for Trailhead Playground

### ISSUE THREAD

**Issue by LoryHFHForce** [trailheadapps/ebikes-lwc#603]
From step 6 when I tried to deploy the app to my org, I got these errors:

Component Failures [16]
==================================================================================================================================================================================
| Type    Name                                 Problem
| ─────── ──────────────────────────────────── ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
| Error   Default_E-Bikes                      Audience needs at least one criteria.
| Warning ebikeslogo                           This record isn't in the target org: E-Bikes.
| Error   E_Bikes                              Error parsing file: Unexpected element {http://soap.sforce.com/2006/04/metadata}siteType during simple type deserialization (31:15)
| Error   E_Bikes1                             In field: Network - no Network named E-Bikes found
| Error   Default_Navigation                   In field: Network - no Network named E-Bikes found
| Error   SFDC_Default_Navigation_EUU002dBikes In field: Network - no Network named E-Bikes found
| Error   E-Bikes                              In field: PicassoSite - no SiteDotCom named E_Bikes1 found
| Error   cbE_Bikes                            Network not found for the CustomBrand : cbE_Bikes
| Error   E_Bikes                              Error parsing file: Unexpected element {http://soap.sforce.com/2006/04/metadata}siteType during simple type deserialization
| Error   E-Bikes                              In field: PicassoSite - no SiteDotCom named E_Bikes1 found
| Error   cbE_Bikes                            Network not found for the CustomBrand : cbE_Bikes
| Error   Default_Navigation                   In field: Network - no Network named E-Bikes found
| Error   SFDC_Default_Navigation_EUU002dBikes In field: Network - no Network named E-Bikes found
| Error   Default_E-Bikes                      Audience needs at least one criteria.
| Warning ebikeslogo                           This record isn't in the target org: E-Bikes.
| Error   E_Bikes1                             In field: Network - no Network named E-Bikes found

Hence, I am unable to complete the module https://trailhead.salesforce.com/content/learn/projects/quick-start-ebikes-sample-app?trailmix_creator_id=strailhead&trailmix_slug=quest-dreamforce-2023-developer

**Comment by pozil** [comment]
Hi @LoryHFHForce and sorry for the delay. I saw that you closed the other issue.
Did you manage to deploy the app?

**Comment by LoryHFHForce** [comment]
Hi @pozil , it was end-user error for this newbie. I found out I had to make sure I hit Delete again when deleting the custom Product object.

**Comment by pozil** [comment]
It can happen to everyone :) I'm glad that you were able to deploy the app.
