### ISSUE TITLE
Issue in deployment

### ISSUE THREAD

**Issue by jyotisingh3** [trailheadapps/ebikes-lwc#61]
I am trying to deploy it in a new Dev org where no customizations are present but on step 9 I am getting below error - 

1.force-app\main\default\sites\E_Bikes.site-meta.xml                In field: siteAdmin - no User named test-yofedql671ah@example.com found

2.force-app\main\default\siteDotComSites\E_Bikes_C.site-meta.xml    Error parsing file: Element {http://soap.sforce.com/2006/04/metadata}siteAdmin invalid at this location in type SiteDotCom (5:16)

### Steps To Reproduce:

1.  Followed all the prior steps.

**Comment by muenzpraeger** [comment]
Please follow step 7.
