### ISSUE TITLE
Product Explorer page: components are not dragging or dropping

### ISSUE THREAD

**Issue by annyhe** [trailheadapps/ebikes-lwc#62]
### Summary

products on the productTileList component used to be drag and drop. Now on drag, the mouse highlights the component instead of moving it. 

### Steps To Reproduce:

1.  Follow the instructions to deploy this app to an org
2.  Go to host/lightning/n/Product_Explorer 
3. Attempt to drag a product from the center component by clicking on it and holding down the left key.

### Expected result

The product(s) move from the grid to the details component, to the right of the productTileList component.

### Actual result

The product(s) are highlighted and do not move from the grid

### Additional information

<img width="1552" alt="Screen Shot 2019-07-26 at 6 34 57 PM" src="https://user-images.githubusercontent.com/17040750/61988282-1c0c3380-afd4-11e9-8b76-33672f5fa661.png">

**Comment by muenzpraeger** [comment]
Dragging was never available on the `Product Explorer`. It’s a capability of the bike selection on the `Reseller Orders` record page.
