### ISSUE TITLE
Not available for deploy for this organization

### ISSUE THREAD

**Issue by forcelearn** [trailheadapps/ebikes-lwc#63]
I have followed steps to install into developer org. Dev hub is enabled in org and connected that org in vscode facing the above error

D:\Salesforce\LWC Recipes\ebikes-lwc>sfdx force:source:push
PROJECT PATH                                                                                       ERROR
─────────────────────────────────────────────────────────────────────────────────────────────────  ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
force-app\main\default\networks\E-Bikes.network-meta.xml                                           Not available for deploy for this organization
force-app\main\default\objects\Product_Family__c\listViews\All_Product_Families.listView-meta.xml  SharedTo not allowed:roleAndSubordinatesInternal -
CEO (106:19)
force-app\main\default\objects\Account\listViews\All_Acounts.listView-meta.xml                     SharedTo not allowed:roleAndSubordinatesInternal -
CEO (103:19)
force-app\main\default\sites\E_Bikes.site-meta.xml                                                 Communities must be enabled before deploying a Chatter Network Site
force-app\main\default\siteDotComSites\E_Bikes_C.site                                              You don't have the correct site publisher privileges for this operation Site : E-Bikes, type: Site.com Community(db=C,api=ChatterNetworkPicasso)
force-app\main\default\networkBranding\cbE_Bikes.networkBranding                                   Network not found for the CustomBrand : cbE_Bikes
force-app\main\default\layouts\Case-Case Layout.layout-meta.xml                                    In field: QuickAction - no QuickAction named Case.CaseComment found
ERROR running force:source:push:  Push failed.

**Comment by muenzpraeger** [comment]
You didn’t enable `Communities` as stated in step 3 of the instructions.

**Comment by miteshmsharma** [comment]
I have the same issue. Which step 3 mentions about enabling communities?

**Comment by miteshmsharma** [comment]
After enabling community my deploy failed with following error:

C:\Users\Dell\trail-comp\ebikes-lwc>sfdx force:source:deploy -p force-app -u de
eloper@lwc.com
PROJECT PATH                                                          ERROR
────────────────────────────────────────────────────────────────────  ─────────
───────────────────────────────────────────────────────────────────────────────
force-app\main\default\objects\Case\fields\Product__c.field-meta.xml  Cannot up
ate a field to a Lookup, MasterDetail, or Hierarchy from something else (44:13)
force-app\main\default\sites\E_Bikes.site-meta.xml                    In field:
siteAdmin - no User named test-yofedql671ah@example.com found
force-app\main\default\networks\E-Bikes.network-meta.xml              In field:
Site - no CustomSite named E_Bikes found
force-app\main\default\networkBranding\cbE_Bikes.networkBranding      Network n
t found for the CustomBrand : cbE_Bikes
force-app\main\default\siteDotComSites\E_Bikes_C.site                 In field:
Network - no Network named E-Bikes found
ERROR running force:source:deploy:  Deploy failed.

Can you please help

**Comment by muenzpraeger** [comment]
Resolve this error which is related to the `Case` object in your org.

```
force-app\main\default\objects\Case\fields\Product__c.field-meta.xml Cannot up
ate a field to a Lookup, MasterDetail, or Hierarchy from something else
```

**Comment by chernyy-svyat** [comment]
In the 7 step of [Installing E-Bikes a Developer Edition Org](https://github.com/trailheadapps/ebikes-lwc#installing-e-bikes-using-a-developer-edition-org) you can leave:
```
<?xml version="1.0" encoding="UTF-8" ?>
<SiteDotCom xmlns="http://soap.sforce.com/2006/04/metadata">
    <label>E-Bikes</label>
    <siteType>ChatterNetworkPicasso</siteType>
</SiteDotCom>
```
Salesforce can automatically set `siteAdmin` in the target to the user that launched the delpoyment. And also Salesforce can set `subdomain` to the value from the target Dev Org. Of course the communities should be enabled and the subdomain should be specified.

**Comment by aewatson** [comment]
I was following the Lightning Web Components Basics > Push and Deploy Lightning Web Component Files trailhead and ran into all the issues documented here including another. I hadn't enabled Communities, the Case.Product__c field already existed as a picklist from a previous Trailhead exercise so the new field for E-bikes would not deploy, and the site admin user configured for the Community was some test user (perhaps from the scratch org).

Here is a concise list of steps I had to follow in my dev hub org:

- Enable Communities - Setup > Feature Settings > Communitites > Community Settings
- Rename existing Case.Product__c field api name to "Product2__c"
- Edit SiteAdmin property in file force-app/main/default/sites/E_bikes.site-meta.xml to use my dev hub username

Successful deploy after doing the above.

**Comment by ohmorale** [comment]
> I was following the Lightning Web Components Basics > Push and Deploy Lightning Web Component Files trailhead and ran into all the issues documented here including another. I hadn't enabled Communities, the Case.Product__c field already existed as a picklist from a previous Trailhead exercise so the new field for E-bikes would not deploy, and the site admin user configured for the Community was some test user (perhaps from the scratch org).
> 
> Here is a concise list of steps I had to follow in my dev hub org:
> 
> * Enable Communities - Setup > Feature Settings > Communitites > Community Settings
> * Rename existing Case.Product__c field api name to "Product2__c"
> * Edit SiteAdmin property in file force-app/main/default/sites/E_bikes.site-meta.xml to use my dev hub username
> 
> Successful deploy after doing the above.

Thanks for the guidance, it save me a lot of time. Thanks again :)

**Comment by tpiechota** [comment]
> I was following the Lightning Web Components Basics > Push and Deploy Lightning Web Component Files trailhead and ran into all the issues documented here including another. I hadn't enabled Communities, the Case.Product__c field already existed as a picklist from a previous Trailhead exercise so the new field for E-bikes would not deploy, and the site admin user configured for the Community was some test user (perhaps from the scratch org).
> 
> Here is a concise list of steps I had to follow in my dev hub org:
> 
> * Enable Communities - Setup > Feature Settings > Communitites > Community Settings
> * Rename existing Case.Product__c field api name to "Product2__c"
> * Edit SiteAdmin property in file force-app/main/default/sites/E_bikes.site-meta.xml to use my dev hub username
> 
> Successful deploy after doing the above.

Thanks very much, that worked for me beautifully.

On top of the steps above I also had to update
force-app/main/default/profiles/E-Bikes Profile.profile-meta.xml to resolve "In field: userLicense - no UserLicense named Guest User License found" and change 
<userLicense>Guest User License</userLicense> to <userLicense>Salesforce</userLicense>

**Comment by mtemanuel** [comment]
I have been trying to complete the deploy and push module in the trailhead and I am getting the following errors, I have enabled communities and there is no custom Product on case:
rror  force-app/main/default/objects/Account/listViews/All_Acounts.listView-meta.xml                     In field: roleAndSubordinatesInternal - no Role named CEO found (103:19)
Error  force-app/main/default/objects/Product_Family__c/listViews/All_Product_Families.listView-meta.xml  In field: roleAndSubordinatesInternal - no Role named CEO found (106:19)
Error  force-app/main/default/profiles/E-Bikes Profile.profile-meta.xml                                   You can not create custom Guest profiles.
Error  force-app/main/default/layouts/Case-Case Layout.layout-meta.xml                                    In field: QuickAction - no QuickAction named Case.CaseComment found
Error  force-app/main/default/flexipages/Account_Record_Page.flexipage-meta.xml                           Your org doesn't have access to component cooper:companyInsightTeaserCard.
ERROR running force:source:deploy:  Deploy failed

**Comment by squattingdog** [comment]
if you get something like this:
SOURCE PROGRESS | ██████████████████████████░░░░░░░░░░░░░░ | 88/135 Files
TYPE   PROJECT PATH                                               PROBLEM
─────  ─────────────────────────────────────────────────────────  ──────────────────────────────────────────────
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  force-app/main/default/experiences/E_Bikes1.site-meta.xml  Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
Error  N/A                                                        Not available for deploy for this organization
ERROR running force:source:deploy:  Deploy failed.


Be sure that "Enable ExperienceBundle Metadata API" is enabled in the Community Settings --> Community Management Settings set of checkboxes.  

I created a few new dev orgs and this feature was not enabled by default.  The scratch org that is created in the "scratch org code push" instructions has the setting enabled in the definition file.

**Comment by pozil** [comment]
Great point @squattingdog, thanks for sharing, I'll update the readme.

**Comment by lcx8866** [comment]
I have been trying to complete the deploy and push module in a Developer Edition Org and I am getting the following errors
↓
Error  unpackaged/profiles/E-Bikes Profile.profile-meta.xml          E-Bikes Profile     You can not create custom Guest profiles.

**Comment by SHUBHAM-DHANUKA** [comment]
force-app\main\default\layouts\Case-Case Layout.layout-meta.xml In field: QuickAction - no QuickAction named Case.CaseComment found

Does that error also gets resolved by enabling the community?

**Comment by Samyalamuri** [comment]
![Screenshot 2024-04-24 143128](https://github.com/trailheadapps/ebikes-lwc/assets/112501442/e438226b-04e3-4519-a4a7-291b5d5f6c28)

How do i clear this error ?
Please help
