### ISSUE TITLE
This is linked from a trailhead and the instructions break the trailhead

### ISSUE THREAD

**Issue by joeythomaschaske** [trailheadapps/ebikes-lwc#64]
This repo is linked from [this trailhead](https://trailhead.salesforce.com/en/content/learn/modules/lightning-web-components-basics/push-lightning-web-component-files?trail_id=build-lightning-web-components). The trailhead says to follow the instructions in this repo, however, if you follow all the steps and activate the community you will not be able to complete the trailhead because it has you deploy this repo to a developer org but you will get deployment errors about the community.

These steps need to be updated to point that out, or the trailhead needs to be clearer instead of pointing to these directions

**Comment by muenzpraeger** [comment]
Can you please post the deployment errors? If you look at the closed issues you’ll see several ones that confirmed the successful usage of the repo with a Trailhead Playground (aka Developer Edition).

**Comment by joeythomaschaske** [comment]
Well I may have spoke too soon. I attempted to retry the trailhead without setting up the community and I am still getting errors. These are a subset of the original errors I was receiving which I do not have saved.

```
force-app/main/default/networks/E-Bikes.network-meta.xml                                           Not available for deploy for this organization
force-app/main/default/objects/Account/listViews/All_Acounts.listView-meta.xml                     SharedTo not allowed:roleAndSubordinatesInternal - CEO (103:19)
force-app/main/default/objects/Product_Family__c/listViews/All_Product_Families.listView-meta.xml  SharedTo not allowed:roleAndSubordinatesInternal - CEO (106:19)
force-app/main/default/objects/Case/fields/Product__c.field-meta.xml                               Cannot update a field to a Lookup, MasterDetail, or Hierarchy from something else (44:13)
force-app/main/default/sites/E_Bikes.site-meta.xml                                                 Communities must be enabled before deploying a Chatter Network Site
force-app/main/default/siteDotComSites/E_Bikes_C.site                                              You don't have the correct site publisher privileges for this operation Site : E-Bikes, type: Site.com Community(db=C,api=ChatterNetworkPicasso)
force-app/main/default/networkBranding/cbE_Bikes.networkBranding                                   Network not found for the CustomBrand : cbE_Bikes
force-app/main/default/layouts/Case-Case Layout.layout-meta.xml                                    In field: QuickAction - no QuickAction named Case.CaseComment found
ERROR running force:source:deploy:  Deploy failed.
```

I do remember some of them being about not being able to deploy a network or site

**Comment by joeythomaschaske** [comment]
It helps if I read the steps for deploying to a developer org in the repo.

I've got it working, thank you for your time.

**Comment by dmorenoatk** [comment]
I'm facing the same issue. Tried two times from scratch but can't seem to get pass this error. Could you tell me how you managed to solve it?

**Comment by DimaFSK** [comment]
> I'm facing the same issue. Tried two times from scratch but can't seem to get pass this error. Could you tell me how you managed to solve it?

@dmorenoatk, is this problem still actual for you? If so, then try to follow the steps from "Installing E-Bikes using a Developer Edition Org" chapter on https://github.com/trailheadapps/ebikes-lwc#installing-e-bikes-using-a-developer-edition-org. And it does not matter you are acting in Developer Edition or Trailhead Playground (in TP you even have MyDomain already enabled).

**Comment by dmorenoatk** [comment]
@DimaFSK, I ended up doing just that and I was able to solve it. Thanks for the reply!

**Comment by Marcelovv2** [comment]
on the mention instructions: 
3. In Setup, under Communities Settings, click the **Enable communities checkbox**, and then select and register a subdomain for your community.

But when I go there I see this: "Enable Community Workspaces" is it the same thing?

4. In Setup, under Object Manager, delete the custom Product picklist field from the Case object.

I see the case object but the custom part it's empty. 


Any ideas? please
