### ISSUE TITLE
Aura linting script in package.json doesn't find matching files

### ISSUE THREAD

**Issue by pozil** [trailheadapps/ebikes-lwc#88]
### Summary
Aura linting script in package.json doesn't find matching files

### Steps To Reproduce:

Run `npm run lint:aura`

### Expected result

Script should run on files and potentially report linting errors.
```bash
'Search for "**/*.js" in folder "**/aura/"'
' -> Ignoring: **/node_modules/**,**/jsdoc/**,**/htdocs/**,**/invalidTest/**,**/purposelyInvalid/**,**/invalidTestData/**,**/validationTest/**,**/lintTest/**,**/target/**,**/parseError/**,**/*.junk.js,**/*_mock?.js'
Found 8 matching files.
```

### Actual result

```bash
'Search for "**/*.js" in folder "**/aura/"'
' -> Ignoring: **/node_modules/**,**/jsdoc/**,**/htdocs/**,**/invalidTest/**,**/purposelyInvalid/**,**/invalidTestData/**,**/validationTest/**,**/lintTest/**,**/target/**,**/parseError/**,**/*.junk.js,**/*_mock?.js'
 ▸    Did not find matching files.
```

**Comment by pozil** [comment]
The following command fails in the context of npm execution (it does work from the CLI):
```bash
sfdx force:lightning:lint **/aura/**
```

**Comment by pozil** [comment]
Recommended fix is to update `lint:aura` script in `package.json` to:
```
sfdx force:lightning:lint force-app/main/default/aura/**
```

**Comment by muenzpraeger** [comment]
That fix doesn't count in different package directories.

**Comment by pozil** [comment]
true, but it doesn't look like we can have a wildcard prefix for that ATM.

**Comment by muenzpraeger** [comment]
According to the docs it supports glob patterns.

This works for example in `eBikes` => `sfdx force:lightning:lint **/aura`

**Comment by pozil** [comment]
Yes it works if you type that in the CLI directly but it doesn't work when it's run by npm.

**Comment by pozil** [comment]
Issue is tracked here: https://github.com/forcedotcom/cli/issues/196

**Comment by pozil** [comment]
Issue fixed with current CLI version.
