### ISSUE TITLE
bikeCustomizer component is not displaying

### ISSUE THREAD

**Issue by fabricepierre** [trailheadapps/ebikes-lwc#94]
lightning:container cool demo looks broken
I was wondering where / how we can demo the bikeCustomizer component.
I tried to add it in a product record page and it generate few javascript errors. this was a really cool demo any plan to get it fixed?

**Comment by pozil** [comment]
Thanks for reaching out @fabricepierre. It's not broken but we do need to put it back in the Community navigation menu:

![Screenshot 2019-10-14 at 14 58 43](https://user-images.githubusercontent.com/5071767/66753139-67c3d000-ee93-11e9-9884-478d1aac1e6b.png)

**Comment by pozil** [comment]
Also, the JS errors you got were related to CSP. This component loads the 3D model from AWS and we've only whitelisted that for Community use. You can apply the whitelist to all context if you want to use the component in Lightning Experience.

**Comment by fabricepierre** [comment]
tried with very no luck, updated the CSP context to All

Access to XMLHttpRequest at 'https://s3-us-west-1.amazonaws.com/e-bikes/bike.babylon' from origin 'https://enterprise-customer-9288-dev-ed--c.container.lightning.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by muenzpraeger** [comment]
@pozil What's the status of this?

**Comment by pozil** [comment]
@muenzpraeger as discussed offline earlier, I'm still airing on the side of removing it from the repo.
Any counter advice?
