### ISSUE TITLE
Unexpected file found in package directory

### ISSUE THREAD

**Issue by dirceuvjr** [trailheadapps/ebikes-lwc#96]
### Summary

Following the steps to install e-bikes to a trailhead org, I encountered the following error while executing step 5 (Push the app to your scratch org):

ebikes-lwc sfdx force:source:push
ERROR running force:source:push:  Unexpected file found in package directory: ~/ebikes-lwc/force-app/main/default/navigationMenus/Default_Navigation.navigationMenu-meta.xml

### Steps To Reproduce:

Execute steps throw 1 to 5

### Expected result

ebikes app pushed to scratch org

### Actual result

Error as stated in the summary

**Comment by pozil** [comment]
Hi thanks for reporting this. This is likely the same cause as issue as #97.
Can you update your CLI and plugins then retry to deploy?

**Comment by dirceuvjr** [comment]
Hi @pozil after updating the CLI it worked fine. Thanks for the assistance.
