### ISSUE TITLE
Issues with deployment

### ISSUE THREAD

**Issue by vardanvapartners** [trailheadapps/ebikes-lwc#97]
Running into issues deploying this with my scratch org

I tried this last week and it was working, so it has to do with some recent updates.
Here are the errors:

Error  shape/settings/Security.settings             Security                               Property 'enableSetPasswordInApi' not valid in version 46.0
Error  shape/settings/Communities.settings          settings/Communities.settings          Not available for deploy for this API version
Error  shape/settings/LightningExperience.settings  settings/LightningExperience.settings  Not available for deploy for this API version

### Steps To Reproduce:

1. Create a new trailhead playground account
2. Clone the repository (
git clone https://github.com/trailheadapps/ebikes-lwc
cd ebikes-lwc )
3. Create Scratch Org and provide it with Alias:
sfdx force:org:create -s -f config/project-scratch-def.json -a ebikes

At this point the creation of the scratch org fails.

![error creating scratch org](https://user-images.githubusercontent.com/56379530/66789064-da867880-ee9e-11e9-9bba-f0cd73e95ab5.jpg)

**Comment by pozil** [comment]
Hi @vardanvapartners, looks like you are trying to deploy with the wrong API version (v46.0). Salesforce Orgs and this repository were upgraded to Winter '20 (API v47.0) this weekend.
Can you make sure that your CLI and DX plugin are up to date and retry to deploy?

**Comment by pozil** [comment]
Run `sfdx update` to update CLI and plugins.

**Comment by sardito** [comment]
I had the same issue. It worked for me with the update command (thanks @pozil ).

**Comment by tschroedertn** [comment]
I also had the same issue and this worked for me.  Thanks @pozil !

**Comment by akhileshpendharkar** [comment]
This worked for me

**Comment by chemchem88** [comment]
works for me thanks :)

**Comment by vardanvapartners** [comment]
Yes, the update fixes the issue- thank you!

**Comment by Elliot128** [comment]
I have the exact same issue and errors.

Running `sfdx update` does not fix this for me. Already on latest version `7.31.0`

**Comment by bizoregon** [comment]
Thanks @pozil!

**Comment by narendrasalesforce** [comment]
Awesome, Ran the command (sfdx update) from Visual Studio code terminal.
It worked. Thanks
